### ISSUE TITLE
$#,##0_);($#,##0);"-" does not work for negative numbers

### ISSUE THREAD

**Issue by tinkermachine** [SheetJS/ssf#40] opened 2019-12-16 23:28 UTC
Format: $#,##0_);($#,##0);"-"

Current output: (2$,000)

Desired output: ($2,000)

**Comment by jgdovin** [comment] 2019-12-23 18:32
This is a duplicate of #31

**Comment by tinkermachine** [comment] 2020-04-07 05:25
Is there an update to this?

**Comment by SheetJSDev** [comment] 2020-05-09 05:02
Fixed in 0.11.0

**Closed by SheetJSDev** 2020-05-09 05:02 UTC
